title:              MokLab
email:              lightnlight93@gmail.com
description:        low level knowledge, security analysist
author:             hanteok
baseurl:            ""
url:                "https://hanteok.github.io"

# Social Profiles
twitter_username:   hanteok25
github_username:    hanteok
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-167485484-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
